name: githubactions

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  githubactions:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    
    - name: Run Action
      uses: github/githubactions
      env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
