name: githubactions

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  githubactions:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    
